project14/urls.py
from django.contrib import admin
from django.urls import path,include
from ganaric.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ammu/',ammu,name='ammu'),
    path('rani/',rani,name='rani'),
    path('spasific/',include('spasific.urls')),
]

spasific/urls.py
from spasific.views import *

from django.urls import path

app_name='anything'

urlpatterns=[
    path('bablu/',bablu,name='bablu'),
    path('hansi/',hansi,name='hansi'),
]

ganaric/models.py
from django.db import models

# Create your models here.

spasific/models.py
from django.db import models

# Create your models here.

ganaric/views.py
from django.shortcuts import render

# Create your views here.
def ammu(request):
    return render(request,'ammu.html')
def rani(request):
    return render(request,'rani.html')

spasific/views.py
from django.shortcuts import render

# Create your views here.
def bablu(request):
    return render(request,'bablu.html')

def hansi(request):
    return render(request,'hansi.html')

templates/ammu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>hi rani nice to meet u</h1>
        <a href="{% url 'rani' %}">rani responce</a>
    </center>
</body>
</html>

templates/bablu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>hansi wt r u doing now</h1>
        <a href="{% url 'anything:hansi' %}">hansi responce</a>
    </center>
</body>
</html>

templates/hansi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>hey bablu ntg </h1>
        <a href="{% url 'anything:bablu' %}">bablu reaction</a>
    </center>
</body>
</html>

templates/rani.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>hello ammu nice what about u</h1>
        <a href="{% url 'ammu' %}">ammu reaction</a>
    </center>
</body>
</html>